name: Merge and PR into 2023.2

run-name: Merge 2022.3 -> 2023.2
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'maintenance/mps20223'

jobs:
  merge-and-pr:
    # only trigger if it was actually merged
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/PR-into-next-version.yml
    with:
      from-version: 2022.3
      from-branch: maintenance/mps20223
      to-version: 2023.2
      to-branch: maintenance/mps20232
